
tasks:
  - init: npm install
    command: npm run start



vscode:
  extensions:
    - esbenp.prettier-vscodeintroduction/learn-gitpod/gitpod-yaml)
    - ritwickdey.LiveServer# and commit this file to your remote git repository to share the goodness with others.
    - mhutchie.git-graph# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
    - dbaeumer.vscode-eslinttasks:
  - init: npm install && npm run build
    command: npm run start
